# ===================================
#  List Behavior Config
# ===================================

title: Iris Sunburst Charts
list: @/plugins/delphinium/iris/models/home/columns.yaml
modelClass: Delphinium\Iris\Models\Home
recordUrl: delphinium/iris/home/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSorting: true
showCheckboxes: true
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



