# ===================================
#  Form Behavior Config
# ===================================

name: LTI Configuration
form: @/plugins/delphinium/roots/models/developer/fields.yaml
modelClass: Delphinium\Roots\Models\Developer
defaultRedirect: delphinium/roots/lticonfiguration

create:
    title: New LTI Configuration
    redirect: delphinium/roots/configuration/update/:id
    redirectClose: delphinium/roots/lticonfiguration
    flash-save: LTI configuration added

update:
    title: Edit LTI Configuration
    redirect: delphinium/roots/lticonfiguration
    flash-save: LTI configuration successfully updated
    flash-delete: LTI configuration has been deleted