# ===================================
#  Form Behavior Config
# ===================================

name: LTI Configuration
<<<<<<< HEAD
<<<<<<< HEAD
form: $/delphinium/roots/models/developer/fields.yaml
=======
form: ~/plugins/delphinium/roots/models/developer/fields.yaml
>>>>>>> b2e80ac3a6c3869578b563140dcb761ad5044817
=======
form: ~/plugins/delphinium/roots/models/developer/fields.yaml
>>>>>>> 458e203e636a22db079d0e2b12c60aa91cba5e3b
modelClass: Delphinium\Roots\Models\Developer
defaultRedirect: delphinium/roots/lticonfiguration

create:
    title: New LTI Configuration
    redirect: delphinium/roots/configuration/update/:id
    redirectClose: delphinium/roots/lticonfiguration
    flash-save: LTI configuration added

update:
    title: Edit LTI Configuration
    redirect: delphinium/roots/lticonfiguration
    flash-save: LTI configuration successfully updated
    flash-delete: LTI configuration has been deleted