# ===================================
#  List Behavior Config
# ===================================

title: LTI Configurations
<<<<<<< HEAD
<<<<<<< HEAD
list: $/delphinium/roots/models/developer/columns.yaml
=======
list: ~/plugins/delphinium/roots/models/developer/columns.yaml
>>>>>>> b2e80ac3a6c3869578b563140dcb761ad5044817
=======
list: ~/plugins/delphinium/roots/models/developer/columns.yaml
>>>>>>> 458e203e636a22db079d0e2b12c60aa91cba5e3b
modelClass: Delphinium\Roots\Models\Developer
recordUrl: delphinium/roots/lticonfiguration/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSorting: true
showCheckboxes: true
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



