# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Newcontent

# Model Form Field configuration
form: $/delphinium/vanilla/models/newcontent/fields.yaml

# Model Class name
modelClass: Delphinium\Vanilla\Models\Newcontent

# Default redirect location
defaultRedirect: delphinium/vanilla/newcontent

# Create page
create:
    title: Create Newcontent
    redirect: delphinium/vanilla/newcontent/update/:id
    redirectClose: delphinium/vanilla/newcontent

# Update page
update:
    title: Edit Newcontent
    redirect: delphinium/vanilla/newcontent
    redirectClose: delphinium/vanilla/newcontent

# Preview page
preview:
    title: Preview Newcontent