# ===================================
#  Form Behavior Config
# ===================================

name: Dev
<<<<<<< HEAD
<<<<<<< HEAD
form: $/delphinium/dev/models/configuration/fields.yaml
=======
form: ~/plugins/delphinium/dev/models/configuration/fields.yaml
>>>>>>> b2e80ac3a6c3869578b563140dcb761ad5044817
=======
form: ~/plugins/delphinium/dev/models/configuration/fields.yaml
>>>>>>> 458e203e636a22db079d0e2b12c60aa91cba5e3b
modelClass: Delphinium\Dev\Models\Configuration
defaultRedirect: delphinium/dev/configuration

create:
    title: New Dev Configuration
    redirect: delphinium/dev/configuration/update/:id
    redirectClose: delphinium/dev/configuration
    flash-save: Dev configuration added

update:
    title: Edit Dev Configuration
    redirect: delphinium/dev/configuration
    redirectClose: delphinium/dev/configuration
    flash-save: Dev configuration successfully updated
    flash-delete: Dev configuration has been deleted