# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Attendance

# Model Form Field configuration
form: $/delphinium/blossom/models/attendance/fields.yaml

# Model Class name
modelClass: Delphinium\Blossom\Models\Attendance

# Default redirect location
defaultRedirect: delphinium/blossom/attendance

# Create page
create:
    title: Create Attendance
    redirect: delphinium/blossom/attendance/update/:id
    redirectClose: delphinium/blossom/attendance

# Update page
update:
    title: Edit Attendance
    redirect: delphinium/blossom/attendance
    redirectClose: delphinium/blossom/attendance

# Preview page
preview:
    title: Preview Attendance