# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Attendance Session

# Model Form Field configuration
form: $/delphinium/blossom/models/attendancesession/fields.yaml

# Model Class name
modelClass: Delphinium\Blossom\Models\AttendanceSession

# Default redirect location
defaultRedirect: delphinium/blossom/attendancesessions

# Create page
create:
    title: Create Attendance Session
    redirect: delphinium/blossom/attendancesessions/update/:id
    redirectClose: delphinium/blossom/attendancesessions

# Update page
update:
    title: Edit Attendance Session
    redirect: delphinium/blossom/attendancesessions
    redirectClose: delphinium/blossom/attendancesessions

# Preview page
preview:
    title: Preview Attendance Session