name: Vanilla
modelClass: Delphinium\Vanilla\Models\Vanilla
form: $/delphinium/vanilla/models/vanilla/fields.yaml
defaultRedirect: delphinium/vanilla/vanilla
create:
    redirect: 'delphinium/vanilla/vanilla/update/:id'
    redirectClose: delphinium/vanilla/vanilla
update:
    redirect: delphinium/vanilla/vanilla
    redirectClose: delphinium/vanilla/vanilla
