# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Gradebook

# Model Form Field configuration
form: $/delphinium/blossom/models/gradebook/fields.yaml

# Model Class name
modelClass: Delphinium\Blossom\Models\Gradebook

# Default redirect location
defaultRedirect: delphinium/blossom/Gradebook

# Create page
create:
    title: Create Gradebook
    redirect: delphinium/blossom/gradebook/update/:id
    redirectClose: delphinium/blossom/gradebook

# Update page
update:
    title: Edit Gradebook
    redirect: delphinium/blossom/gradebook
    redirectClose: delphinium/blossom/gradebook

# Preview page
preview:
    title: Preview Gradebook