# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Competencies

# Model Form Field configuration
form: $/delphinium/blossom/models/competencies/fields.yaml

# Model Class name
modelClass: Delphinium\Blossom\Models\Competencies

# Default redirect location
defaultRedirect: delphinium/blossom/competencies

# Create page
create:
    title: Create Competencies
    redirect: delphinium/blossom/competencies/update/:id
    redirectClose: delphinium/blossom/competencies

# Update page
update:
    title: Edit Competencies
    redirect: delphinium/blossom/competencies
    redirectClose: delphinium/blossom/competencies

