name: Modulemap
modelClass: Delphinium\BirdoParadise\Models\Modulemap
form: $/delphinium/birdoparadise/models/modulemap/fields.yaml
defaultRedirect: delphinium/birdoparadise/modulemap
create:
    title: 'Create Modulemap'
    redirect: 'delphinium/birdoparadise/modulemap/update/:id'
    redirectClose: delphinium/birdoparadise/modulemap
update:
    title: 'Edit Modulemap'
    redirect: delphinium/birdoparadise/modulemap
    redirectClose: delphinium/birdoparadise/modulemap
preview:
    title: 'Preview Modulemap'
