# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Delphiniumize

# Model Form Field configuration
form: $/delphinium/vanilla/models/delphiniumize/fields.yaml

# Model Class name
modelClass: Delphinium\Vanilla\Models\Delphiniumize

# Default redirect location
defaultRedirect: delphinium/vanilla/delphiniumize

# Create page
create:
    title: Create Delphiniumize
    redirect: delphinium/vanilla/delphiniumize/update/:id
    redirectClose: delphinium/vanilla/delphiniumize

# Update page
update:
    title: Edit Delphiniumize
    redirect: delphinium/vanilla/delphiniumize
    redirectClose: delphinium/vanilla/delphiniumize

# Preview page
preview:
    title: Preview Delphiniumize