# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Popquiz

# Model Form Field configuration
form: $/delphinium/poppies/models/popquiz/fields.yaml

# Model Class name
modelClass: Delphinium\Poppies\Models\Popquiz

# Default redirect location
defaultRedirect: delphinium/poppies/popquiz

# Create page
create:
    title: Create Popquiz
    redirect: delphinium/poppies/popquiz/update/:id
    redirectClose: delphinium/poppies/popquiz

# Update page
update:
    title: Edit Popquiz
    redirect: delphinium/poppies/popquiz
    redirectClose: delphinium/poppies/popquiz

# Preview page
preview:
    title: Preview Popquiz